In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\91904\Downloads\WHR26_Data_Figure_2.1.csv")
df

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2025,1,Finland,7.764,7.690,7.837,1.915,1.638,0.939,1.105,0.093,0.491,1.582
1,2025,2,Iceland,7.540,7.449,7.630,1.971,1.720,0.996,1.105,0.187,0.187,1.373
2,2025,3,Denmark,7.539,7.446,7.631,1.986,1.633,0.930,1.081,0.125,0.474,1.310
3,2025,4,Costa Rica,7.439,7.356,7.522,1.697,1.483,0.739,1.101,0.059,0.122,2.236
4,2025,5,Sweden,7.255,7.172,7.337,1.950,1.570,1.027,1.070,0.149,0.447,1.041
...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,2023,139,DR Congo,3.295,3.128,3.462,0.534,0.665,0.262,0.473,0.189,0.072,1.102
433,2023,140,Sierra Leone,3.245,3.124,3.366,0.654,0.566,0.253,0.469,0.181,0.053,1.068
434,2023,141,Lesotho,3.186,2.904,3.469,0.771,0.851,0.000,0.523,0.082,0.085,0.875
435,2023,142,Lebanon,2.707,2.616,2.797,1.377,0.577,0.556,0.173,0.068,0.029,-0.073
436,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.000,0.242,0.000,0.091,0.088,0.672

In [3]:
len(df[df['Country name']=="Bahrain"])

3

In [4]:
len(df[df['Year']==2025])

147

In [5]:
len(df[df['Year']==2024])

147

In [6]:
len(df[df['Year']==2023])

143

In [7]:
Tot_con=[[len(df[df['Year']==2025]), len(df[df['Year']==2024]), len(df[df['Year']==2023])]]
k=pd.DataFrame(Tot_con, columns=["2025","2024","2023"], index=["Total countries"])
k.index.name="Year"
print(k)

                 2025  2024  2023
Year
Total countries   147   147   143

In [8]:
df.filter(items=['Country name', 'Rank'])

     Country name  Rank
0         Finland     1
1         Iceland     2
2         Denmark     3
3      Costa Rica     4
4          Sweden     5
..            ...   ...
432      DR Congo   139
433  Sierra Leone   140
434       Lesotho   141
435       Lebanon   142
436   Afghanistan   143

[437 rows x 2 columns]

In [9]:
df['Country name'].where(df['Country name']=='Bahrain')

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
432    NaN
433    NaN
434    NaN
435    NaN
436    NaN
Name: Country name, Length: 437, dtype: str

In [10]:
df.loc[df['Country name']=='Bahrain']

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
54,2025,55,Bahrain,6.254,6.143,6.364,1.930,1.293,0.693,1.055,0.143,0.171,0.969
205,2024,59,Bahrain,6.030,5.891,6.170,1.752,1.391,0.609,0.907,0.148,0.167,1.057
355,2023,62,Bahrain,5.959,5.766,6.153,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
dd=df[df['Log GDP per capita'].isna()]

In [12]:
dd

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
355,2023,62,Bahrain,5.959,5.766,6.153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,2023,88,Tajikistan,5.281,5.201,5.361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,2023,103,State of Palestine,4.879,4.753,5.006,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
dd[dd['Country name']=='Bahrain']

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
355,2023,62,Bahrain,5.959,5.766,6.153,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df['Log GDP per capita']=df['Log GDP per capita'].fillna(df['Log GDP per capita'].mean())

In [15]:
print(df['Log GDP per capita'])

0      1.915
1      1.971
2      1.986
3      1.697
4      1.950
       ...
432    0.534
433    0.654
434    0.771
435    1.377
436    0.628
Name: Log GDP per capita, Length: 437, dtype: float64

In [16]:
dd=df[df['Social support'].isna()]

In [17]:
dd

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
355,2023,62,Bahrain,5.959,5.766,6.153,1.411329,NaN,NaN,NaN,NaN,NaN,NaN
381,2023,88,Tajikistan,5.281,5.201,5.361,1.411329,NaN,NaN,NaN,NaN,NaN,NaN
396,2023,103,State of Palestine,4.879,4.753,5.006,1.411329,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 437 entries, 0 to 436
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            437 non-null    int64
 1   Rank                            437 non-null    int64
 2   Country name                    437 non-null    str
 3   Life evaluation-3 year average  437 non-null    float64
 4   Lower whisker                   437 non-null    float64
 5   Upper whisker                   437 non-null    float64
 6   Log GDP per capita              437 non-null    float64
 7   Social support                  434 non-null    float64
 8   Healthy life expectancy         432 non-null    float64
 9   Freedom to make life choices    432 non-null    float64
 10  Generosity                      434 non-null    float64
 11  Perceptions of corruption       433 non-null    float64
 12  Dystopia + residual             429 non-null    float64
dtypes: float64(10), int64(2), str(1)
memory usage: 44.5 KB

In [20]:
df.describe()

,Year,Rank,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
count,437.000000,437.000000,437.000000,437.000000,437.00000,437.000000,434.000000,432.000000,432.000000,434.000000,433.000000,429.000000
mean,2024.009153,73.345538,5.585730,5.474208,5.69722,1.411329,1.225611,0.563417,0.752535,0.121615,0.149649,1.366904
std,0.815508,42.118575,1.154143,1.167207,1.14202,0.403239,0.355309,0.221905,0.203769,0.064477,0.116503,0.551497
min,2023.000000,1.000000,1.364000,1.301000,1.42700,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.295000
25%,2023.000000,37.000000,4.674000,4.549000,4.79400,1.149000,0.996000,0.416750,0.630500,0.075000,0.069000,1.047000
50%,2024.000000,73.000000,5.846000,5.727000,5.96300,1.445000,1.315500,0.564000,0.767000,0.115500,0.118000,1.396000
75%,2025.000000,110.000000,6.492000,6.390000,6.59900,1.738000,1.500750,0.702000,0.902500,0.156750,0.188000,1.741000
max,2025.000000,147.000000,7.764000,7.690000,7.83700,2.167000,1.840000,1.238000,1.147000,0.401000,0.575000,2.998000

In [22]:
df['Social support']=df['Social support'].fillna(df['Social support'].median())

In [23]:
df.isnull().sum()

Year                              0
Rank                              0
Country name                      0
Life evaluation-3 year average    0
Lower whisker                     0
Upper whisker                     0
Log GDP per capita                0
Social support                    0
Healthy life expectancy           5
Freedom to make life choices      5
Generosity                        3
Perceptions of corruption         4
Dystopia + residual               8
dtype: int64

In [25]:
df.fillna({'Healthy life expectancy':df['Healthy life expectancy'].median()},inplace=True)

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2025,1,Finland,7.764,7.690,7.837,1.915,1.638,0.939,1.105,0.093,0.491,1.582
1,2025,2,Iceland,7.540,7.449,7.630,1.971,1.720,0.996,1.105,0.187,0.187,1.373
2,2025,3,Denmark,7.539,7.446,7.631,1.986,1.633,0.930,1.081,0.125,0.474,1.310
3,2025,4,Costa Rica,7.439,7.356,7.522,1.697,1.483,0.739,1.101,0.059,0.122,2.236
4,2025,5,Sweden,7.255,7.172,7.337,1.950,1.570,1.027,1.070,0.149,0.447,1.041
...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,2023,139,DR Congo,3.295,3.128,3.462,0.534,0.665,0.262,0.473,0.189,0.072,1.102
433,2023,140,Sierra Leone,3.245,3.124,3.366,0.654,0.566,0.253,0.469,0.181,0.053,1.068
434,2023,141,Lesotho,3.186,2.904,3.469,0.771,0.851,0.000,0.523,0.082,0.085,0.875
435,2023,142,Lebanon,2.707,2.616,2.797,1.377,0.577,0.556,0.173,0.068,0.029,-0.073
436,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.000,0.242,0.000,0.091,0.088,0.672

In [26]:
df.loc[df['Country name']=='Bahrain']

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
54,2025,55,Bahrain,6.254,6.143,6.364,1.930000,1.2930,0.693,1.055,0.143,0.171,0.969
205,2024,59,Bahrain,6.030,5.891,6.170,1.752000,1.3910,0.609,0.907,0.148,0.167,1.057
355,2023,62,Bahrain,5.959,5.766,6.153,1.411329,1.3155,0.564,NaN,NaN,NaN,NaN

In [27]:
df.fillna({'Freedom to make life choices':df['Freedom to make life choices'].median()},inplace=True)

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2025,1,Finland,7.764,7.690,7.837,1.915,1.638,0.939,1.105,0.093,0.491,1.582
1,2025,2,Iceland,7.540,7.449,7.630,1.971,1.720,0.996,1.105,0.187,0.187,1.373
2,2025,3,Denmark,7.539,7.446,7.631,1.986,1.633,0.930,1.081,0.125,0.474,1.310
3,2025,4,Costa Rica,7.439,7.356,7.522,1.697,1.483,0.739,1.101,0.059,0.122,2.236
4,2025,5,Sweden,7.255,7.172,7.337,1.950,1.570,1.027,1.070,0.149,0.447,1.041
...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,2023,139,DR Congo,3.295,3.128,3.462,0.534,0.665,0.262,0.473,0.189,0.072,1.102
433,2023,140,Sierra Leone,3.245,3.124,3.366,0.654,0.566,0.253,0.469,0.181,0.053,1.068
434,2023,141,Lesotho,3.186,2.904,3.469,0.771,0.851,0.000,0.523,0.082,0.085,0.875
435,2023,142,Lebanon,2.707,2.616,2.797,1.377,0.577,0.556,0.173,0.068,0.029,-0.073
436,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.000,0.242,0.000,0.091,0.088,0.672

In [28]:
df.fillna({'Generosity':df['Generosity'].median()},inplace=True)

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,2025,1,Finland,7.764,7.690,7.837,1.915,1.638,0.939,1.105,0.093,0.491,1.582
1,2025,2,Iceland,7.540,7.449,7.630,1.971,1.720,0.996,1.105,0.187,0.187,1.373
2,2025,3,Denmark,7.539,7.446,7.631,1.986,1.633,0.930,1.081,0.125,0.474,1.310
3,2025,4,Costa Rica,7.439,7.356,7.522,1.697,1.483,0.739,1.101,0.059,0.122,2.236
4,2025,5,Sweden,7.255,7.172,7.337,1.950,1.570,1.027,1.070,0.149,0.447,1.041
...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,2023,139,DR Congo,3.295,3.128,3.462,0.534,0.665,0.262,0.473,0.189,0.072,1.102
433,2023,140,Sierra Leone,3.245,3.124,3.366,0.654,0.566,0.253,0.469,0.181,0.053,1.068
434,2023,141,Lesotho,3.186,2.904,3.469,0.771,0.851,0.000,0.523,0.082,0.085,0.875
435,2023,142,Lebanon,2.707,2.616,2.797,1.377,0.577,0.556,0.173,0.068,0.029,-0.073
436,2023,143,Afghanistan,1.721,1.667,1.775,0.628,0.000,0.242,0.000,0.091,0.088,0.672

In [34]:
#df.fillna({'Generosity':df['Generosity'].median()},inplace=True)

df[df["Country name"]=="Tajikistan"]

,Year,Rank,Country name,Life evaluation-3 year average,Lower whisker,Upper whisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
87,2025,88,Tajikistan,5.591,5.513,5.669,1.180000,1.4760,0.783,0.767,0.0850,0.336,NaN
236,2024,90,Tajikistan,5.411,5.337,5.485,0.914000,1.5550,0.658,0.767,0.0850,0.342,NaN
381,2023,88,Tajikistan,5.281,5.201,5.361,1.411329,1.3155,0.564,0.767,0.1155,NaN,NaN