In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\91904\Downloads\Sample.csv")

In [4]:
df

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
0,1,2025-01-03,P1001,Electronics,C001,South,2,1200,5,UPI,300,0,0.8,0
1,2,2025-01-03,P1002,Clothing,C002,South,1,800,10,Credit Card,300,0,0.8,0
2,3,2025-01-04,P1003,Grocery,C003,North,5,200,0,Cash,150,0,0.7,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
4,5,2025-01-06,P1004,Home,C005,East,3,500,15,Debit Card,250,0,0.5,1
5,6,2025-01-10,P1002,Clothing,C006,South,2,800,5,UPI,500,1,0.9,0
6,7,2025-01-12,P1005,Grocery,C007,North,10,100,0,Cash,100,0,0.6,0
7,8,2025-01-15,P1001,Electronics,C008,West,1,1200,10,Credit Card,600,0,0.7,0
8,9,2025-01-18,P1006,Beauty,C009,South,4,300,0,UPI,200,0,0.8,0
9,10,2025-01-20,P1003,Grocery,C010,East,6,200,5,Cash,150,0,0.5,0
10,11,2025-02-01,P1002,Clothing,C011,South,1,800,0,UPI,400,0,0.6,0
11,12,2025-02-03,P1004,Home,C012,North,2,500,10,Debit Card,350,0,0.7,0
12,13,2025-02-05,P1001,Electronics,C013,West,3,1200,5,Credit Card,700,0,0.8,1
13,14,2025-02-07,P1005,Grocery,C014,South,8,100,0,Cash,120,0,0.9,0
14,15,2025-02-10,P1006,Beauty,C015,East,2,300,10,UPI,250,1,0.6,0

In [5]:
df.to_csv(r"C:\Users\91904\Downloads\Sample1.csv")

In [6]:
df.dtypes

order_id                     int64
order_date                  object
product_id                  object
category                    object
customer_id                 object
region                      object
quantity                     int64
unit_price                   int64
discount_pct                 int64
payment_type                object
marketing_spend_at_time      int64
holiday_flag                 int64
weather_score              float64
returned                     int64
dtype: object

In [7]:
df.shape

(15, 14)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 15 non-null     int64
 1   order_date               15 non-null     object
 2   product_id               15 non-null     object
 3   category                 15 non-null     object
 4   customer_id              15 non-null     object
 5   region                   15 non-null     object
 6   quantity                 15 non-null     int64
 7   unit_price               15 non-null     int64
 8   discount_pct             15 non-null     int64
 9   payment_type             15 non-null     object
 10  marketing_spend_at_time  15 non-null     int64
 11  holiday_flag             15 non-null     int64
 12  weather_score            15 non-null     float64
 13  returned                 15 non-null     int64
dtypes: float64(1), int64(7), object(6)
memory usage: 1.8+ KB

In [9]:
df.values

array([[1, '2025-01-03', 'P1001', 'Electronics', 'C001', 'South', 2,
        1200, 5, 'UPI', 300, 0, 0.8, 0],
       [2, '2025-01-03', 'P1002', 'Clothing', 'C002', 'South', 1, 800,
        10, 'Credit Card', 300, 0, 0.8, 0],
       [3, '2025-01-04', 'P1003', 'Grocery', 'C003', 'North', 5, 200, 0,
        'Cash', 150, 0, 0.7, 0],
       [4, '2025-01-05', 'P1001', 'Electronics', 'C004', 'West', 1, 1200,
        0, 'UPI', 400, 0, 0.6, 0],
       [5, '2025-01-06', 'P1004', 'Home', 'C005', 'East', 3, 500, 15,
        'Debit Card', 250, 0, 0.5, 1],
       [6, '2025-01-10', 'P1002', 'Clothing', 'C006', 'South', 2, 800, 5,
        'UPI', 500, 1, 0.9, 0],
       [7, '2025-01-12', 'P1005', 'Grocery', 'C007', 'North', 10, 100, 0,
        'Cash', 100, 0, 0.6, 0],
       [8, '2025-01-15', 'P1001', 'Electronics', 'C008', 'West', 1, 1200,
        10, 'Credit Card', 600, 0, 0.7, 0],
       [9, '2025-01-18', 'P1006', 'Beauty', 'C009', 'South', 4, 300, 0,
        'UPI', 200, 0, 0.8, 0],
       [10, '2025-01-20', 'P1003', 'Grocery', 'C010', 'East', 6, 200, 5,
        'Cash', 150, 0, 0.5, 0],
       [11, '2025-02-01', 'P1002', 'Clothing', 'C011', 'South', 1, 800,
        0, 'UPI', 400, 0, 0.6, 0],
       [12, '2025-02-03', 'P1004', 'Home', 'C012', 'North', 2, 500, 10,
        'Debit Card', 350, 0, 0.7, 0],
       [13, '2025-02-05', 'P1001', 'Electronics', 'C013', 'West', 3,
        1200, 5, 'Credit Card', 700, 0, 0.8, 1],
       [14, '2025-02-07', 'P1005', 'Grocery', 'C014', 'South', 8, 100, 0,
        'Cash', 120, 0, 0.9, 0],
       [15, '2025-02-10', 'P1006', 'Beauty', 'C015', 'East', 2, 300, 10,
        'UPI', 250, 1, 0.6, 0]], dtype=object)

In [10]:
df['customer_id'].astype('int64')

ValueError: invalid literal for int() with base 10: 'C001'

In [ ]:
df['order_id']=df['order_id'].astype('int64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 15 non-null     int64
 1   order_date               15 non-null     object
 2   product_id               15 non-null     object
 3   category                 15 non-null     object
 4   customer_id              15 non-null     object
 5   region                   15 non-null     object
 6   quantity                 15 non-null     int64
 7   unit_price               15 non-null     int64
 8   discount_pct             15 non-null     int64
 9   payment_type             15 non-null     object
 10  marketing_spend_at_time  15 non-null     int64
 11  holiday_flag             15 non-null     int64
 12  weather_score            15 non-null     float64
 13  returned                 15 non-null     int64
dtypes: float64(1), int64(7), object(6)
memory usage: 1.8+ KB

In [ ]:
df[['order_id','category']]

    order_id     category
0          1  Electronics
1          2     Clothing
2          3      Grocery
3          4  Electronics
4          5         Home
5          6     Clothing
6          7      Grocery
7          8  Electronics
8          9       Beauty
9         10      Grocery
10        11     Clothing
11        12         Home
12        13  Electronics
13        14      Grocery
14        15       Beauty

In [ ]:
df['order_id']

(0      1
 1      2
 2      3
 3      4
 4      5
 5      6
 6      7
 7      8
 8      9
 9     10
 10    11
 11    12
 12    13
 13    14
 14    15
 Name: order_id, dtype: int64,
 ['category'])

In [ ]:
df.loc[[2]][['order date']]

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
2,3,2025-01-04,P1003,Grocery,C003,North,5,200,0,Cash,150,0,0.7,0

In [ ]:
df.loc[2,'order_date']="2025-01-03"

In [ ]:
df.loc[2]

order_id                            3
order_date                 2025-01-03
product_id                      P1003
category                      Grocery
customer_id                      C003
region                          North
quantity                            5
unit_price                        200
discount_pct                        0
payment_type                     Cash
marketing_spend_at_time           150
holiday_flag                        0
weather_score                     0.7
returned                            0
Name: 2, dtype: object

In [12]:
df.head(10)

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
0,1,2025-01-03,P1001,Electronics,C001,South,2,1200,5,UPI,300,0,0.8,0
1,2,2025-01-03,P1002,Clothing,C002,South,1,800,10,Credit Card,300,0,0.8,0
2,3,2025-01-04,P1003,Grocery,C003,North,5,200,0,Cash,150,0,0.7,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
4,5,2025-01-06,P1004,Home,C005,East,3,500,15,Debit Card,250,0,0.5,1
5,6,2025-01-10,P1002,Clothing,C006,South,2,800,5,UPI,500,1,0.9,0
6,7,2025-01-12,P1005,Grocery,C007,North,10,100,0,Cash,100,0,0.6,0
7,8,2025-01-15,P1001,Electronics,C008,West,1,1200,10,Credit Card,600,0,0.7,0
8,9,2025-01-18,P1006,Beauty,C009,South,4,300,0,UPI,200,0,0.8,0
9,10,2025-01-20,P1003,Grocery,C010,East,6,200,5,Cash,150,0,0.5,0

In [14]:
df.tail(70)

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
0,1,2025-01-03,P1001,Electronics,C001,South,2,1200,5,UPI,300,0,0.8,0
1,2,2025-01-03,P1002,Clothing,C002,South,1,800,10,Credit Card,300,0,0.8,0
2,3,2025-01-04,P1003,Grocery,C003,North,5,200,0,Cash,150,0,0.7,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
4,5,2025-01-06,P1004,Home,C005,East,3,500,15,Debit Card,250,0,0.5,1
5,6,2025-01-10,P1002,Clothing,C006,South,2,800,5,UPI,500,1,0.9,0
6,7,2025-01-12,P1005,Grocery,C007,North,10,100,0,Cash,100,0,0.6,0
7,8,2025-01-15,P1001,Electronics,C008,West,1,1200,10,Credit Card,600,0,0.7,0
8,9,2025-01-18,P1006,Beauty,C009,South,4,300,0,UPI,200,0,0.8,0
9,10,2025-01-20,P1003,Grocery,C010,East,6,200,5,Cash,150,0,0.5,0
10,11,2025-02-01,P1002,Clothing,C011,South,1,800,0,UPI,400,0,0.6,0
11,12,2025-02-03,P1004,Home,C012,North,2,500,10,Debit Card,350,0,0.7,0
12,13,2025-02-05,P1001,Electronics,C013,West,3,1200,5,Credit Card,700,0,0.8,1
13,14,2025-02-07,P1005,Grocery,C014,South,8,100,0,Cash,120,0,0.9,0
14,15,2025-02-10,P1006,Beauty,C015,East,2,300,10,UPI,250,1,0.6,0

In [16]:
df.sample(5)

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
13,14,2025-02-07,P1005,Grocery,C014,South,8,100,0,Cash,120,0,0.9,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
11,12,2025-02-03,P1004,Home,C012,North,2,500,10,Debit Card,350,0,0.7,0
9,10,2025-01-20,P1003,Grocery,C010,East,6,200,5,Cash,150,0,0.5,0
0,1,2025-01-03,P1001,Electronics,C001,South,2,1200,5,UPI,300,0,0.8,0

In [18]:
df.nlargest(2, 'quantity')

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
6,7,2025-01-12,P1005,Grocery,C007,North,10,100,0,Cash,100,0,0.6,0
13,14,2025-02-07,P1005,Grocery,C014,South,8,100,0,Cash,120,0,0.9,0

In [19]:
df.nsmallest(3, 'quantity')

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
1,2,2025-01-03,P1002,Clothing,C002,South,1,800,10,Credit Card,300,0,0.8,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
7,8,2025-01-15,P1001,Electronics,C008,West,1,1200,10,Credit Card,600,0,0.7,0

In [20]:
df[df.order_id>5]

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
5,6,2025-01-10,P1002,Clothing,C006,South,2,800,5,UPI,500,1,0.9,0
6,7,2025-01-12,P1005,Grocery,C007,North,10,100,0,Cash,100,0,0.6,0
7,8,2025-01-15,P1001,Electronics,C008,West,1,1200,10,Credit Card,600,0,0.7,0
8,9,2025-01-18,P1006,Beauty,C009,South,4,300,0,UPI,200,0,0.8,0
9,10,2025-01-20,P1003,Grocery,C010,East,6,200,5,Cash,150,0,0.5,0
10,11,2025-02-01,P1002,Clothing,C011,South,1,800,0,UPI,400,0,0.6,0
11,12,2025-02-03,P1004,Home,C012,North,2,500,10,Debit Card,350,0,0.7,0
12,13,2025-02-05,P1001,Electronics,C013,West,3,1200,5,Credit Card,700,0,0.8,1
13,14,2025-02-07,P1005,Grocery,C014,South,8,100,0,Cash,120,0,0.9,0
14,15,2025-02-10,P1006,Beauty,C015,East,2,300,10,UPI,250,1,0.6,0

In [ ]:
df[df.order_date<"2025-01-15"]

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
0,1,2025-01-03,P1001,Electronics,C001,South,2,1200,5,UPI,300,0,0.8,0
1,2,2025-01-03,P1002,Clothing,C002,South,1,800,10,Credit Card,300,0,0.8,0
2,3,2025-01-04,P1003,Grocery,C003,North,5,200,0,Cash,150,0,0.7,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
4,5,2025-01-06,P1004,Home,C005,East,3,500,15,Debit Card,250,0,0.5,1
5,6,2025-01-10,P1002,Clothing,C006,South,2,800,5,UPI,500,1,0.9,0
6,7,2025-01-12,P1005,Grocery,C007,North,10,100,0,Cash,100,0,0.6,0

In [25]:
d=pd.to_datetime("2025-01-15")

In [26]:
type(d)

pandas._libs.tslibs.timestamps.Timestamp

In [27]:
d

Timestamp('2025-01-15 00:00:00')

In [28]:
df[df.order_date<d]

TypeError: '<' not supported between instances of 'str' and 'Timestamp'

In [38]:
df.loc[:,'product_id':'unit_price']

   product_id     category customer_id region  quantity  unit_price
0       P1001  Electronics        C001  South         2        1200
1       P1002     Clothing        C002  South         1         800
2       P1003      Grocery        C003  North         5         200
3       P1001  Electronics        C004   West         1        1200
4       P1004         Home        C005   East         3         500
5       P1002     Clothing        C006  South         2         800
6       P1005      Grocery        C007  North        10         100
7       P1001  Electronics        C008   West         1        1200
8       P1006       Beauty        C009  South         4         300
9       P1003      Grocery        C010   East         6         200
10      P1002     Clothing        C011  South         1         800
11      P1004         Home        C012  North         2         500
12      P1001  Electronics        C013   West         3        1200
13      P1005      Grocery        C014  South         8         100
14      P1006       Beauty        C015   East         2         300

In [34]:
df.loc[df['unit_price']>500, ['category','unit_price']]

       category  unit_price
0   Electronics        1200
1      Clothing         800
3   Electronics        1200
5      Clothing         800
7   Electronics        1200
10     Clothing         800
12  Electronics        1200

In [40]:
df.iloc[2:8]

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
2,3,2025-01-04,P1003,Grocery,C003,North,5,200,0,Cash,150,0,0.7,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
4,5,2025-01-06,P1004,Home,C005,East,3,500,15,Debit Card,250,0,0.5,1
5,6,2025-01-10,P1002,Clothing,C006,South,2,800,5,UPI,500,1,0.9,0
6,7,2025-01-12,P1005,Grocery,C007,North,10,100,0,Cash,100,0,0.6,0
7,8,2025-01-15,P1001,Electronics,C008,West,1,1200,10,Credit Card,600,0,0.7,0

In [47]:
df.iloc[:,[3,5,7]]

       category region  unit_price
0   Electronics  South        1200
1      Clothing  South         800
2       Grocery  North         200
3   Electronics   West        1200
4          Home   East         500
5      Clothing  South         800
6       Grocery  North         100
7   Electronics   West        1200
8        Beauty  South         300
9       Grocery   East         200
10     Clothing  South         800
11         Home  North         500
12  Electronics   West        1200
13      Grocery  South         100
14       Beauty   East         300

In [49]:
df.at[14, 'unit_price']

np.int64(300)

In [50]:
df.iat[1,2]

'P1002'

In [51]:
df.at[14, 'unit_price']=900

In [52]:
df.at[14, 'unit_price']

np.int64(900)

In [53]:
df.filter(items=['category', 'unit_price'])

       category  unit_price
0   Electronics        1200
1      Clothing         800
2       Grocery         200
3   Electronics        1200
4          Home         500
5      Clothing         800
6       Grocery         100
7   Electronics        1200
8        Beauty         300
9       Grocery         200
10     Clothing         800
11         Home         500
12  Electronics        1200
13      Grocery         100
14       Beauty         900

In [59]:
df.filter(items=["category"])

       category
0   Electronics
1      Clothing
2       Grocery
3   Electronics
4          Home
5      Clothing
6       Grocery
7   Electronics
8        Beauty
9       Grocery
10     Clothing
11         Home
12  Electronics
13      Grocery
14       Beauty

In [61]:
df['unit_price'].where(df['unit_price']>500)

0     1200.0
1      800.0
2        NaN
3     1200.0
4        NaN
5      800.0
6        NaN
7     1200.0
8        NaN
9        NaN
10     800.0
11       NaN
12    1200.0
13       NaN
14     900.0
Name: unit_price, dtype: float64

In [62]:
df.query('unit_price>700')

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
0,1,2025-01-03,P1001,Electronics,C001,South,2,1200,5,UPI,300,0,0.8,0
1,2,2025-01-03,P1002,Clothing,C002,South,1,800,10,Credit Card,300,0,0.8,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
5,6,2025-01-10,P1002,Clothing,C006,South,2,800,5,UPI,500,1,0.9,0
7,8,2025-01-15,P1001,Electronics,C008,West,1,1200,10,Credit Card,600,0,0.7,0
10,11,2025-02-01,P1002,Clothing,C011,South,1,800,0,UPI,400,0,0.6,0
12,13,2025-02-05,P1001,Electronics,C013,West,3,1200,5,Credit Card,700,0,0.8,1
14,15,2025-02-10,P1006,Beauty,C015,East,2,900,10,UPI,250,1,0.6,0

In [63]:
df

,order_id,order_date,product_id,category,customer_id,region,quantity,unit_price,discount_pct,payment_type,marketing_spend_at_time,holiday_flag,weather_score,returned
0,1,2025-01-03,P1001,Electronics,C001,South,2,1200,5,UPI,300,0,0.8,0
1,2,2025-01-03,P1002,Clothing,C002,South,1,800,10,Credit Card,300,0,0.8,0
2,3,2025-01-04,P1003,Grocery,C003,North,5,200,0,Cash,150,0,0.7,0
3,4,2025-01-05,P1001,Electronics,C004,West,1,1200,0,UPI,400,0,0.6,0
4,5,2025-01-06,P1004,Home,C005,East,3,500,15,Debit Card,250,0,0.5,1
5,6,2025-01-10,P1002,Clothing,C006,South,2,800,5,UPI,500,1,0.9,0
6,7,2025-01-12,P1005,Grocery,C007,North,10,100,0,Cash,100,0,0.6,0
7,8,2025-01-15,P1001,Electronics,C008,West,1,1200,10,Credit Card,600,0,0.7,0
8,9,2025-01-18,P1006,Beauty,C009,South,4,300,0,UPI,200,0,0.8,0
9,10,2025-01-20,P1003,Grocery,C010,East,6,200,5,Cash,150,0,0.5,0
10,11,2025-02-01,P1002,Clothing,C011,South,1,800,0,UPI,400,0,0.6,0
11,12,2025-02-03,P1004,Home,C012,North,2,500,10,Debit Card,350,0,0.7,0
12,13,2025-02-05,P1001,Electronics,C013,West,3,1200,5,Credit Card,700,0,0.8,1
13,14,2025-02-07,P1005,Grocery,C014,South,8,100,0,Cash,120,0,0.9,0
14,15,2025-02-10,P1006,Beauty,C015,East,2,900,10,UPI,250,1,0.6,0

In [64]:
df.groupby('payment_type')['quantity'].sum()

payment_type
Cash           29
Credit Card     5
Debit Card      5
UPI            12
Name: quantity, dtype: int64