In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\91904\Downloads\titanic\test2.csv")

In [3]:
print(df)

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292   NaN        Q
1    female  47.0      1      0              363272    7.0000   NaN        S
2      male  62.0      0      0              240276    9.6875   NaN        Q
3      male  27.0      0      0              315154    8.6625   NaN        S
4    female  22.0      1      1             3101298   12.2875   NaN        S
..      ...   ...    ...    ...                 ...       ...   ...      ...
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S
414  female  39.0      0      0            PC 17758  108.9000  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416    male   NaN      0      0              359309    8.0500   NaN        S
417    male   NaN      1      1                2668   22.3583   NaN        C

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
413         0
414         1
415         0
416         1
417         1

[418 rows x 12 columns]

In [4]:
len(df[df["Survived"]==1])

163

In [5]:
len(df[df["Survived"]==0])

255

In [6]:
df[['Pclass','Survived']]

     Pclass  Survived
0         3         0
1         3         1
2         2         1
3         3         1
4         3         0
..      ...       ...
413       3         0
414       1         1
415       3         0
416       3         1
417       3         1

[418 rows x 2 columns]

In [7]:
len(df[df.Pclass==3])

218

In [8]:
# df['Pclass==1'] where df['Survived==1']

In [9]:
len(df[(df['Pclass']==1) & (df['Survived']==0)])

71

In [10]:
len(df[(df['Pclass']==3) & (df['Survived']==0)])

131

In [11]:
len(df[(df['Pclass']==1) & (df['Age']>18) & (df['Survived']==0)])

60

In [12]:
Data = [10,20,30]
datatable=pd.DataFrame(Data)
datatable

    0
0  10
1  20
2  30

In [13]:
Data = [[10,20,30],[10,20,30]]
datatable=pd.DataFrame(Data, columns=["Number","Age","phone"], index=["A","B"])
datatable

   Number  Age  phone
A      10   20     30
B      10   20     30

In [14]:
Above18=[[len(df[(df['Pclass']==1) & (df['Age']>18) & (df['Survived']==1)]),len(df[(df['Pclass']==2) & (df['Age']>18) & (df['Survived']==1)]),len(df[(df['Pclass']==3) & (df['Age']>18) & (df['Survived']==1)])],[len(df[(df['Pclass']==1) & (df['Age']>18) & (df['Survived']==0)]),len(df[(df['Pclass']==2) & (df['Age']>18) & (df['Survived']==0)]),len(df[(df['Pclass']==3) & (df['Age']>18) & (df['Survived']==0)])]]
c=pd.DataFrame(Above18, columns=["class1", "class2", "class3"], index=["survived","unsurvived"])
c.index.name="Above18"
print(c)

            class1  class2  class3
Above18
survived        33      34      43
unsurvived      60      41      67

In [15]:
Below18=[[len(df[(df['Pclass']==1) & (df['Age']<18) & (df['Survived']==1)]),len(df[(df['Pclass']==2) & (df['Age']<18) & (df['Survived']==1)]),len(df[(df['Pclass']==3) & (df['Age']<18) & (df['Survived']==1)])],[len(df[(df['Pclass']==1) & (df['Age']<18) & (df['Survived']==0)]),len(df[(df['Pclass']==2) & (df['Age']<18) & (df['Survived']==0)]),len(df[(df['Pclass']==3) & (df['Age']<18) & (df['Survived']==0)])]]
c=pd.DataFrame(Below18, columns=["class1", "class2", "class3"], index=["survived","unsurvived"])
c.index.name="Below18"
print(c)

            class1  class2  class3
Below18
survived         0       2      12
unsurvived       3       8      16

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
 11  Survived     418 non-null    int64
dtypes: float64(2), int64(5), str(5)
memory usage: 39.3 KB

In [21]:
df.describe()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Survived
count,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000,418.000000
mean,1100.500000,2.265550,30.272590,0.447368,0.392344,35.627188,0.389952
std,120.810458,0.841838,14.181209,0.896760,0.981429,55.907576,0.488324
min,892.000000,1.000000,0.170000,0.000000,0.000000,0.000000,0.000000
25%,996.250000,1.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,1100.500000,3.000000,27.000000,0.000000,0.000000,14.454200,0.000000
75%,1204.750000,3.000000,39.000000,1.000000,0.000000,31.500000,1.000000
max,1309.000000,3.000000,76.000000,8.000000,9.000000,512.329200,1.000000

In [20]:
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
Survived         0
dtype: int64

In [23]:
df.fillna({'Age':df['Age'].median()},inplace=True)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,1
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,1
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0
416,1308,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S,1
417,1309,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C,1

In [29]:
df.drop(columns=['Cabin'], inplace=True)

In [30]:
df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
Survived       0
FamilySize     0
dtype: int64

In [31]:
df['FamilySize']=df['SibSp']+df['Parch']+1

In [32]:
df['IsAlone']=(df['FamilySize']==1).astype(int)

In [34]:
df['AgeGroup']=pd.cut(df['Age'], bins=[0,10,20,40,60,100], labels=['Child','Teen','Adult','Midage','Senior'])

In [35]:
df['FareGroup']=pd.qcut(df['Fare'],4,labels=['Low','Medium','High','VeryHigh'])

In [37]:
df['Title']=df['Name'].str.extract(' ([A-Za-z]+)\\.', expand=False)

In [38]:
print("AgeGroup distribution: ")
print(df['AgeGroup'].value_counts())

AgeGroup distribution:
AgeGroup
Adult     272
Midage     66
Teen       47
Child      22
Senior     11
Name: count, dtype: int64

In [39]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived,FamilySize,IsAlone,AgeGroup,FareGroup,Title
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,0,1,1,Adult,Low,Mr
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,1,2,0,Midage,Low,Mrs
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,1,1,1,Senior,Medium,Mr
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,1,1,1,Adult,Medium,Mr
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,0,3,0,Adult,Medium,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,S,0,1,1,Adult,Medium,Mr
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C,1,1,1,Adult,VeryHigh,Dona
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S,0,1,1,Adult,Low,Mr
416,1308,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,S,1,1,1,Adult,Medium,Mr
417,1309,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,C,1,3,0,Adult,High,Master

In [ ]:
len(df[(df['Sex']=='Male') & (df['Age']>0)])

0

In [59]:
len(df[df['Sex']=='male'])

266

In [53]:
len(df[df['Sex']=='female'])

152

In [ ]:
df.groupby("Sex").count()['PassengerId']

Sex
female    152
male      266
Name: PassengerId, dtype: int64

In [67]:
df.groupby("Age").count()['PassengerId']

Age
0.17     1
0.33     1
0.75     1
0.83     1
0.92     1
        ..
62.00    1
63.00    2
64.00    3
67.00    1
76.00    1
Name: PassengerId, Length: 79, dtype: int64

In [68]:
df.groupby("AgeGroup").count()['PassengerId']

AgeGroup
Child      22
Teen       47
Adult     272
Midage     66
Senior     11
Name: PassengerId, dtype: int64